version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - filipdujmusic
  ignore:
  - dependency-name: google-protobuf
    versions:
    - 3.14.0
    - 3.15.1
    - 3.15.3
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: redis
    versions:
    - 3.1.0
  - dependency-name: bull
    versions:
    - 3.20.0
    - 3.20.1
    - 3.21.1
    - 3.22.0
  - dependency-name: grpc
    versions:
    - 1.24.4
    - 1.24.5
    - 1.24.6
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.95.1
    - 0.95.2
  - dependency-name: winston-daily-rotate-file
    versions:
    - 4.5.1
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: amqplib
    versions:
    - 0.7.0
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: prom-client
    versions:
    - 13.1.0
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: ini
    versions:
    - 1.3.7
