version: '3'

services:
  db:
    build:
      context: ./db
    image: ae-middleware-db
    ports:
      - 5432:5432

  ae-node:
    image: aeternity/aeternity:v5.5.4
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - ${PWD}/node/config/singlenode_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/config/accounts_test.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
    ports:
     - "3013:3013"
     - "3113:3113"
     - "3014:3014"

  sophia-compiler:
    image: aeternity/aesophia_http:v4.3.2
    ports:
       - "3080:3080"
  
  auto-funder:
    image: ampnet/auto-funder:local
    environment:
      QUEUE_DB_HOST: db
      NODE_URL: http://ae-node:3013
      NODE_INTERNAL_URL: http://ae-node:3113
      COMPILER_URL: http://sophia-compiler:3080
      FUNDERS: 707881878eacacce4db463de9c7bf858b95c3144d52fafed4a41ffd666597d0393d23cf31fcd12324cd45d4784d08953e8df8283d129f357463e6795b40e88aa
    restart: always
    depends_on:
      - ae-node
      - sophia-compiler
      - db
